/** Dimensions available for comparing and breaking down traffic (Umami's useFields). */
export const FIELDS = [
  { name: 'path', label: 'Page' },
  { name: 'query', label: 'Query' },
  { name: 'title', label: 'Page title' },
  { name: 'referrer', label: 'Referrer' },
  { name: 'country', label: 'Country' },
  { name: 'region', label: 'Region' },
  { name: 'city', label: 'City' },
  { name: 'browser', label: 'Browser' },
  { name: 'os', label: 'OS' },
  { name: 'device', label: 'Device' },
  { name: 'utmSource', label: 'UTM source' },
  { name: 'utmMedium', label: 'UTM medium' },
  { name: 'utmCampaign', label: 'UTM campaign' },
  { name: 'utmContent', label: 'UTM content' },
  { name: 'utmTerm', label: 'UTM term' },
  { name: 'hostname', label: 'Hostname' },
  { name: 'distinctId', label: 'User ID' },
  { name: 'tag', label: 'Tag' },
  { name: 'event', label: 'Event' },
] as const;

/** Metric types the /metrics endpoint accepts, for the compare view. */
export const COMPARE_TYPES = [
  { type: 'path', label: 'Pages' },
  { type: 'entry', label: 'Entry pages' },
  { type: 'exit', label: 'Exit pages' },
  { type: 'title', label: 'Page titles' },
  { type: 'referrer', label: 'Referrers' },
  { type: 'channel', label: 'Channels' },
  { type: 'browser', label: 'Browsers' },
  { type: 'os', label: 'Operating systems' },
  { type: 'device', label: 'Devices' },
  { type: 'screen', label: 'Screens' },
  { type: 'country', label: 'Countries' },
  { type: 'region', label: 'Regions' },
  { type: 'city', label: 'Cities' },
  { type: 'language', label: 'Languages' },
  { type: 'event', label: 'Events' },
  { type: 'hostname', label: 'Hostnames' },
  { type: 'utmSource', label: 'UTM source' },
  { type: 'utmMedium', label: 'UTM medium' },
  { type: 'utmCampaign', label: 'UTM campaign' },
  { type: 'tag', label: 'Tags' },
] as const;
